name: steps_ahead
version: 0.0.1+1
publish_to: none
description: 'Steps Ahead - Motivating Steps: Personal Footsteps, Fitness Tracker (SAFT)'
repository: https://github.com/GAM3RG33K/steps_ahead
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  app_settings: ^5.1.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  fluttertoast: ^8.2.4
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  pedometer: ^4.0.1
  permission_handler: ^11.1.0
  quiver: ^3.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  pubspec_dependency_sorter: ^1.0.4
  flutter_test:
    sdk: flutter
flutter_icons:
  android: ic_launcher
  image_path: assets/icons/logo.png
  ios: true
  remove_alpha_ios: true
flutter:
  assets:
    - assets/icons/logo-transparent.png
    - assets/icons/logo_lottie.json
    - assets/progress/tree-1/
  uses-material-design: true
